http:
  base_url: 192.168.0.108:8123

tts:
  - platform: google_translate
    base_url: http://192.168.0.108:8123
    service_name: google_say

default_config:
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml

homeassistant:
  packages: !include_dir_named packages/

airvisual:
    api_key: 99081203-0ce3-4453-9571-c55b05e985a1
    geographies:
        city: Saint Louis
        state: Missouri
        country: USA

discovery:

wyzeapi:
  username: kylevbrocato@gmail.com
  password: Thisone1!

binary_sensor:
  - platform: wyzesense
    device: "/dev/hidraw0"

input_boolean:
  speech_notifications:
    name: Speech Notifications
    icon: mdi:speaker-wireless
    initial: on

input_text:
  card_containers:
    initial: Containers
  software_version:
    initial: Version

weather:
  - platform: darksky
    api_key: aaa9ace222c860c39fb4ef5cc5c4811e

dyson:
  username: kylevbrocato@gmail.com
  password: Thisone1!
  language: GB

google:
  client_id: 487611813533-5gkko6l74dcdlttl1vijc859qoart4cc.apps.googleusercontent.com
  client_secret: 73Sn5pw0ohpXKOIMNTHQWHtS

stream:
camera:
  - platform: ffmpeg
    name: Kitchen Cam
    input: rtsp://kyle:kyle@192.168.0.118/live
