- platform: template
  switches:

      # XBOX HARMONY ACTIVITY
      xbox_one:
        value_template: "{{ is_state_attr('remote.harmony_hub_2', 'current_activity', 'Xbox One') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub_2
            activity: 'Xbox One'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub_2
            activity: 'PowerOff'

      # SWITCH HARMONY ACTIVITY
      switch:
        value_template: "{{ is_state_attr('remote.harmony_hub_2', 'current_activity', 'Switch') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub_2
            activity: 'Switch'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub_2
            activity: 'PowerOff'

      # TV HARMONY ACTIVITY
      tv:
        value_template: "{{ is_state_attr('remote.harmony_hub_2', 'current_activity', 'TV') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub_2
            activity: 'TV'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub_2
            activity: 'PowerOff'
