# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/scenes.html

 scenes:
   - entity: scene.new_scene
     icon: fas:sun
     icon_color: '#ffffff'
     background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
   - entity: scene.purple_orange
     icon: fas:couch
     icon_color: '#ffffff'
     background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
   - entity: scene.late_night
     icon: fas:moon
     icon_color: '#ffffff'
     background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
