###################################
## Door Chime
###################################

- alias: Door Chime
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.wyzesense_778e1096

  condition:
    - condition: state
      entity_id: group.people
      state: 'home'

  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_display
        volume_level: 0.6

    - service: media_player.play_media
      data_template:
        entity_id:
          media_player.bedroom_display
        media_content_id: >
          {% if trigger.to_state.state == 'on' %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/one-tone-chime.mp3
          {% else %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/two-tone-chime.mp3
          {% endif %}
        media_content_type: audio/mp4
