#################################################################
## Media Player Automations
#################################################################

        ##########################################################
        ## Plex Lights On
        ##########################################################

- alias: Media - Plex Stopped Lights On
  trigger:
    - platform: state
      entity_id:
        - media_player.plex_plex_for_apple_tv_bedroom
        - media_player.plex_plex_for_xbox_one_xboxone
        - media_player.plex_plex_for_apple_tv_bruhcato
        - media_player.plex_slivingston010_plex_for_apple_tv_bedroom
        - media_player.plex_slivingston010_plex_for_xbox_one_xboxone
        - media_player.plex_slivingston010_plex_for_apple_tv_bruhcato
      to: 'idle'
      for:
        hours: 0
        minutes: 0
        seconds: 3
    - platform: state
      entity_id:
        - media_player.plex_plex_for_apple_tv_bedroom
        - media_player.plex_plex_for_xbox_one_xboxone
        - media_player.plex_plex_for_apple_tv_bruhcato
        - media_player.plex_slivingston010_plex_for_apple_tv_bedroom
        - media_player.plex_slivingston010_plex_for_xbox_one_xboxone
        - media_player.plex_slivingston010_plex_for_apple_tv_bruhcato
      to: 'paused'
      for:
        hours: 0
        minutes: 0
        seconds: 3

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: group.all_lights
      data:
       transition: 5
       color_temp: 447
       brightness_pct: 65

       ##########################################################
               ## Plex Lights Off
               ##########################################################
- alias: Media - Plex Started Lights Off
  trigger:
    - platform: state
      entity_id:
        - media_player.plex_plex_for_apple_tv_bedroom
        - media_player.plex_plex_for_xbox_one_xboxone
        - media_player.plex_plex_for_apple_tv_bruhcato
        - media_player.plex_slivingston010_plex_for_apple_tv_bedroom
        - media_player.plex_slivingston010_plex_for_xbox_one_xboxone
        - media_player.plex_slivingston010_plex_for_apple_tv_bruhcato
      to: 'playing'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
      data:
       transition: 15
       brightness_pct: 5
